version 1
Denis5201/DenCalculatorCompose pull request #1
Opened 2023-02-24 12:58 UTC by Denis5201

2023-02-26 08:46 UTC, Chantreck requested changes

2023-02-26 08:46 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            }
Можно сделать универсальный компонент ряда, просто внутри логика немного будет зависеть от количества переданных кнопок. Ведь последние две кнопки все равно всегда одинаковые. Также можно сделать матрицу кнопок и просто проходиться по ней, для каждого списка создавая ряд

2023-02-26 08:46 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            SimpleInputRow(modifier = Modifier.weight(1f), listOf("AC", "±", "%", "÷"), viewModel)
Давай сделаем enum для кнопок, а в ряд передавать будем его. Сравнивать строки не очень хорошо, поэтому во вью модели так обрабатывать будет проще)

2023-02-26 08:46 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +        onClick = { viewModel.getInputByClicking(sign) },
Вместо передачи viewModel целиком, достаточно просто передавать лямбду

2023-02-26 08:46 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            text = if (isError) stringResource(R.string.error) else input,
Чтобы не делать кучу проверок, можно сделать data class UiState, в котором будут передаваться из viewModel все необходимые параметры: цвет текста, сам текст и так далее. Прочитать можно [здесь ](https://developer.android.com/topic/architecture/ui-layer), на хабре есть перевод, если нужен

2023-02-26 08:46 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +    var input = mutableStateOf("")
Не совсем корректно использовать mutableState, потому что это все-таки compose-specific штука, а вью модели должно быть без разницы, какой ui-фреймворк используется. Лучше использовать старую-добрую LiveData, а написать можно так:
```kotlin
private val _input = MutableLiveData<String>() 
val input: LiveData<String> get() = _input
```

2023-02-26 08:46 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +    private var number1 = ""
Выноси строки, использующиеся в коде, в строковые константы

2023-02-26 08:46 UTC, Chantreck commented
Исправления можно делать в этой же ветке, они автоматически добавятся в реквест

2023-02-26 17:11 UTC, Denis5201 commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            text = if (isError) stringResource(R.string.error) else input,
Думаю для цвета и текста не лучшая идея делать это. UiState очень удобно использовать, когда на экране необходимо использовать несколько следующих свойств isLoading, isError, message, и для списков, элементы которых приходят от БД или сетевого запроса...(В статье это как раз и делается).
Также для цветов, которые хранятся в MaterialTheme, или для строк, которые лежат в ресурсах, нужен Context, который пробрасывать во ViewModel нельзя

2023-03-07 08:25 UTC, Chantreck requested changes
В целом хорошая работа, в следующий раз, думаю, получишь аппрув)

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            text = if (isError!!) stringResource(R.string.error) else input!!,
Всё же не стоит злоупотреблять `!!` и лучше делать проверку на `null`. К тому же здесь от `nullable` можно легко избавиться, если в `observeAsState` задать начальное значение

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +        }
Это можно было даже сделать через цикл `for (i in 1 until listSign.size - 1)`, но и как и у тебя тоже возможно

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            modifier = Modifier.padding(top = 60.dp),
`modifier` принято указывать последним в списке аргументов

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            thickness = 1.dp, color = lineColor
Не пиши несколько аргументов в одну строку, если уже начал расписывать их в несколько строк. Либо всё в одну, либо все по отдельности)

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +        }
Можно вынести в отдельный компонент, который будет принимать аргумент `isEnabled`, чтобы не повторять проверку на пустоту результата, к тому же так добавится семантика такой проверке

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +fun CalculatorButton(sign: CalcButton, isGray: Boolean, click: (CalcButton) -> Unit, modifier: Modifier) {
На мой взгляд, названия параметра `isGray` не самое удачное, можно использовать `isAccent` или какой-то другой аналог, который отражает суть кнопки. Привязываться к цвету не очень удачно, ведь он может поменяться (например, появится светлая тема или ты захочешь реализовать динамические темы), к тому же на самом деле на макете кнопки не серые, а сиреневого оттенка

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/Constants.kt
> +object Constants {
Если константы используются только в одном классе (а вроде как так и есть), то лучше их объявлять в `private companion object` этого самого класса, иначе если какой-то другой класс начнет использовать эти константы, а они внезапно изменятся, то это может привести к непредсказуемым последствиям. Принцип единственной ответственности, все дела. Отдельно константы стоит выносить только если нам обязательно, чтобы у нескольких классов было одинаковое значение

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +        if (_input.value!!.isNotEmpty()) {
Можно применить инверсию условия, чтобы уменьшить уровень вложенности. В данном случае вполне можно написать `if (!_input.value!!.isNotEmpty()) return`, поскольку после условия нет никаких других действий

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +            CalcButton.PLUSMINUS -> change()
Давай добавим `Sign` в название функции `change`, чтобы было понятнее, что именно она меняет. А то вдруг значение выражения вообще меняется, а не просто знак

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +            number2.isNotEmpty() && operation.isNotEmpty()) {
Длинные условия лучше не переносить, а выносить в отдельную функцию. Например (над названием сильно не думал, просто для примера):
```kotlin
private fun getResult() {
    if (checkInput()) {
        // вычисления
    }
}

private fun checkInput() = 
    setSecondNumberAndCheck() && number1.isNotEmpty() && number2.isNotEmpty() && operation.isNotEmpty()
```
Так понятнее, какую проверку осуществляет это условие. К тому же так проще сделать инверсию условия и уменьшить вложенность)

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +                CalcButton.DIVISION.name -> number1.toDouble() / number2.toDouble()
Здесь ты сам себе усложняешь жизнь. Сначала ты получаешь на вход `CalcButton`, кладешь текстовое представление, а потом по нему ищешь действие. Можно сделать проще и просто в operation класть сам `enum`, тогда не будет сравнения строк (которое неявно сейчас происходит), а оно не очень эффективно

2023-03-07 08:25 UTC, Chantreck commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +            setStringResult(result)
Логика практически полностью повторяется с `getResult`, надо бы что-нибудь с этим сделать. По идее вообще при нажатии на процент просто текущее число должно уменьшаться в 100 раз вне зависимости от предыдущих операций

2023-03-07 14:33 UTC, Denis5201 commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorScreen.kt
> +            modifier = Modifier.padding(top = 60.dp),
На странице документации по [modifier](https://developer.android.com/jetpack/compose/modifiers), в конце 1-го абзаца есть ссылка на [часть](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#elements-accept-and-respect-a-modifier-parameter) другой статьи "рекомендации для compose", где написано "This parameter must be named “modifier” and MUST appear as the **first optional parameter** in the element function's parameter list". В стандартных composable функциях так и есть.
Исправил, где у меня не так.

2023-03-07 17:16 UTC, Denis5201 commented on app/src/main/java/com/example/dencalculatorcompose/CalculatorViewModel.kt
> +            setStringResult(result)
Так работает процент на моём физическом калькуляторе)
Калькулятор на смартфоне уменьшает число в 100 раз, как ты и пишешь, но если это в контексте выражения, то результат считает как у меня.
Но функцию я переработал (сделал 1-у вместо 2-х), и теперь она совмещает весь функционал

2023-03-09 15:48 UTC, Chantreck approved these changes

2023-03-09 15:57 UTC, merged